//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffj//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffjvv
//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffj
//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffj
//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffj
//dkdkkdkakddkdkjfkjfkajdkdfkafkjfkdajfkjfdloremekkloremfkdajffj